=head1 NAME

TwitStreamer -

=head1 SYNOPSIS

  use TwitStreamer;

=head1 DESCRIPTION

TwitStreamer is

=head1 AUTHOR

Motonori Iwata E<lt>gootonori@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

