=head1 NAME

B<streamer.pl> - start stream

=head1 VERSION

0.01

=head1 DESCRIPTION

start twitter stream

=head1 SYNOPSIS

  Options:
    --pit          pit key for twitter(default twitter.com)
    --view|-v      view class(default growl)
    --filter|-f    filter class(default none)

    example)
    $ streamer.pl
    $ streamer.pl -f instagram

=head1 OPTIONS

=item B<--help|-h>

show help message

=item B<--view|-v>

view class(default growl)

=item B<--filter|-f>

filter class(default none)

=head1 AUTHOR

Motonori Iwata

=head1 SEE ALSO


=cut

